---
name: create_cd_artifact_source
description: Grants the ability to create continuous deployment artifact sources
boundaries:
  - instance
available_for:
  - granular_access_token
permissions:
  - create_cd_artifact_source
