---
name: read_cd_artifact_source
description: Grants the ability to read continuous deployment artifact sources
boundaries:
  - instance
available_for:
  - granular_access_token
permissions:
  - read_cd_artifact_source
