---
name: create_repository_storage_move
description: Grants the ability to manage repository storage moves
boundaries:
  - group
  - instance
  - project
available_for:
  - granular_access_token
permissions:
  - create_repository_storage_move
