# frozen_string_literal: true

helper.all_changed_files.each do |filename|
  next unless filename.end_with?('.rb')
  next if filename.start_with?('spec/', 'ee/spec/', 'jh/spec/')

  bulk_database_actions.add_suggestions_for(filename)
end
