---
name: create_offline_export
description: Grants the ability to create offline transfer exports
boundaries:
  - user
available_for:
  - granular_access_token
permissions:
  - create_offline_export
