---
name: autonomous_service_account_execution
description:
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/605895
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/247640
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/613466
milestone: '19.3'
group: group::dap events
type: wip
default_enabled: false
