---
name: duo_workflow_use_hardened_image
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/234036
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/598547
milestone: '19.1'
type: wip
group: group::agent foundations
default_enabled: false
