---
name: granular_personal_access_tokens_enforcement_saas
description: Makes fine-grained personal access token enforcement available on GitLab.com, letting top-level group owners set an enforcement date. If enforcement is enabled, after that date, legacy personal access tokens can no longer access resources in the group, its subgroups, or projects.
feature_issue_url: https://gitlab.com/groups/gitlab-org/-/work_items/20180
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/229817
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/605192
milestone: '19.0'
group: group::authorization
type: wip
default_enabled: false
