---
name: planning_view_boards
description: A new boards experience on the work items page
feature_issue_url: https://gitlab.com/groups/gitlab-org/-/work_items/21748
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/236546
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/601128
milestone: '19.0'
group: group::product planning
type: wip
default_enabled: false
