---
name: rate_limiter_use_labkit_rack_cohort_3
feature_issue_url: https://gitlab.com/gitlab-com/gl-infra/production-engineering/-/work_items/28852
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/239466
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/602804
milestone: '19.1'
type: wip
group: group::networking and incident management
default_enabled: false
