---
name: setting_allow_non_enterprise_placeholder_reassignment
description: Show the group setting to opt in to non-enterprise placeholder reassignment
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/593295
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/253779
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/627781
milestone: '19.4'
group: group::import
type: wip
default_enabled: false
