---
name: read_code_suggestion_connection_detail
description: Grants the ability to read code suggestion connection details
boundaries:
  - user
available_for:
  - granular_access_token
permissions:
  - read_code_suggestion_connection_detail
