# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in gitlab-bitbucket-server.gemspec
gemspec

gem 'gitlab-http', path: '../gitlab-http'
gem 'gitlab-utils', path: '../gitlab-utils'
