---
name: secrets_manager_add_on_enable
description: Triggered when the Secrets Manager paid add-on is enabled for a namespace
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/work_items/612843
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/253618
feature_category: secrets_management
milestone: '19.4'
saved_to_database: true
streamed: true
scope:
- Group
