---
name: read_project_relation_import
description: Grants the ability to read project relation import status
deprecated: true
boundaries:
  - project
available_for:
  - granular_access_token
permissions:
  - read_project_relation_import
