# frozen_string_literal: true

def next?
  File.basename(__FILE__) == "Gemfile.next"
end

source "https://rubygems.org"

# Specify your gem's dependencies in gitlab-backup-cli.gemspec
gemspec

group :development, :test do
  gem 'gitlab-rspec', path: '../gitlab-rspec'
  gem 'pry'
end

gem 'activesupport', '~> 7.2'
