---
name: create_http_integration
description: Grants the ability to create HTTP integrations
boundaries:
  - project
available_for:
  - granular_access_token
permissions:
  - create_http_integration
