import { mountExtended } from 'helpers/vue_test_utils_helper';
import TotpCode from '~/authentication/sessions/components/totp_code.vue';

jest.mock('~/lib/utils/csrf', () => ({ token: 'mock-csrf-token' }));

describe('TotpCode', () => {
  let wrapper;

  const defaultProps = {
    path: '/users/sign_in',
    rememberMe: '1',
    rememberMeEnabled: true,
  };

  const createComponent = (props = {}) => {
    wrapper = mountExtended(TotpCode, {
      propsData: { ...defaultProps, ...props },
    });
  };

  const findIllustration = () => wrapper.find('img');
  const findForm = () => wrapper.find('form');
  const findField = () => wrapper.findByTestId('two-fa-code-field');
  const findVerifyButton = () => wrapper.findByTestId('verify-code-button');
  const findCsrfInput = () => wrapper.find('input[name="authenticity_token"]');
  const findRememberMeInput = () => wrapper.find('input[name="user[remember_me]"]');
  const findMethodInput = () => wrapper.find('input[name="two_factor_method"]');
  const findRecoverButton = () => wrapper.findByTestId('recovery-button');
  const findSecurityDeviceButton = () => wrapper.findByTestId('security-device-button');

  beforeEach(() => {
    createComponent();
  });

  it('renders the illustration', () => {
    expect(findIllustration().exists()).toBe(true);
  });

  it('renders the heading and description', () => {
    expect(wrapper.text()).toContain('Enter authenticator app code');
    expect(wrapper.text()).toContain(
      'Enter the 6-digit one-time passcode generated by your registered authenticator app to verify your identity.',
    );
  });

  it('renders the code field with the expected attributes', () => {
    const field = findField();

    expect(field.attributes('name')).toBe('user[otp_attempt]');
    expect(field.attributes('inputmode')).toBe('numeric');
    expect(field.attributes('autocomplete')).toBe('one-time-code');
    // Canonical id kept for password-manager OTP autofill (parity with the HAML form).
    expect(field.attributes('id')).toBe('user_otp_attempt');
  });

  it('renders the verify button with confirm variant', () => {
    expect(findVerifyButton().props('variant')).toBe('confirm');
  });

  it('renders the form pointing at path with post method', () => {
    expect(findForm().attributes('action')).toBe(defaultProps.path);
    expect(findForm().attributes('method')).toBe('post');
  });

  it('renders the CSRF input', () => {
    expect(findCsrfInput().attributes('value')).toBe('mock-csrf-token');
  });

  it('renders the remember-me input when rememberMeEnabled is true', () => {
    expect(findRememberMeInput().exists()).toBe(true);
    expect(findRememberMeInput().attributes('value')).toBe(defaultProps.rememberMe);
  });

  it('does not render the remember-me input when rememberMeEnabled is false', () => {
    createComponent({ rememberMeEnabled: false });

    expect(findRememberMeInput().exists()).toBe(false);
  });

  it('submits totp as the two_factor_method hint', () => {
    expect(findMethodInput().attributes('value')).toBe('totp');
  });

  it('emits switch-method with "recovery" when the recover button is clicked', () => {
    findRecoverButton().trigger('click');

    expect(wrapper.emitted('switch-method')).toEqual([['recovery']]);
  });

  describe('security device button', () => {
    it('is absent when webauthnEnabled is false', () => {
      expect(findSecurityDeviceButton().exists()).toBe(false);
    });

    it('is present and emits switch-method "webauthn" when webauthnEnabled is true', () => {
      createComponent({ webauthnEnabled: true });

      expect(findSecurityDeviceButton().exists()).toBe(true);

      findSecurityDeviceButton().vm.$emit('click');

      expect(wrapper.emitted('switch-method')).toEqual([['webauthn']]);
    });
  });
});
