---
name: read_alert_metric_image
description: Grants the ability to read alert metric images
boundaries:
  - project
available_for:
  - granular_access_token
permissions:
  - read_alert_metric_image
