---
name: read_user_support_pin
description: Grants the ability to read user support PIN
deprecated: true
boundaries:
  - user
available_for:
  - granular_access_token
permissions:
  - read_user_support_pin
