web: bundle exec unicorn_rails -p $PORT -E development
worker: sudo -u git -i bash -c 'cd $STACK_PATH && bundle exec sidekiq RAILS_ENV=$RAILS_ENV -q post_receive,mailer,system_hook,project_web_hook,common,default,gitlab_shell'
custom_web: bundle exec unicorn_rails -c config/unicorn.rb.cloud66 -E $RAILS_ENV -D
