---
name: read_bulk_import_entity
description: Grants the ability to read GitLab Migration entity details
deprecated: true
boundaries:
  - instance
available_for:
  - granular_access_token
permissions:
  - read_bulk_import_entity
