---
name: create_group_import
description: Grants the ability to create a group import
deprecated: true
boundaries:
  - instance
available_for:
  - granular_access_token
permissions:
  - create_group_import
