---
name: admin
description: Instance-wide administrator with full access to all projects and groups,
  including instance-level settings and custom attributes.
inherits_from:
- owner
project:
  permissions: []
  raw_permissions:
  - delete_custom_attribute
  - read_custom_attribute
  - read_storage_disk_path
  - update_custom_attribute
  - update_max_artifacts_size
group:
  permissions: []
  raw_permissions:
  - delete_custom_attribute
  - lock_namespace_duo_feature
  - read_custom_attribute
  - update_custom_attribute
  - update_max_artifacts_size
organization:
  permissions: []
  raw_permissions:
  - access_organization_admin_area
  - create_group
  - delete_organization
  - read_artifact_registry
  - read_organization
  - read_organization_user
  - read_work_item_type
  - restore_organization
  - transfer_group
  - update_organization
