---
name: delete_package
description: Grants the ability to delete packages
boundaries:
  - group
  - project
available_for:
  - granular_access_token
permissions:
  - delete_conan_package
  - delete_npm_package_tag
  - delete_nuget_package
  - delete_package
