---
name: read_runner_controller_token
description: Grants the ability to read runner controller tokens
boundaries:
  - instance
available_for:
  - granular_access_token
permissions:
  - read_runner_controller_token
