# @feature_category: custom_dashboards_foundation

query getAnalyticsDashboardGroupChildren($fullPath: ID!) {
  group(fullPath: $fullPath) {
    id
    name
    fullName
    fullPath
    projects(first: 100, sort: ACTIVITY_DESC, includeArchived: false) {
      nodes {
        id
        name
        fullName: nameWithNamespace
        fullPath
      }
    }
    descendantGroups(first: 100, includeParentDescendants: false, archived: false) {
      nodes {
        id
        name
        fullName
        fullPath
        projectsCount
        descendantGroupsCount
      }
    }
  }
}
