---
name: create_resource_access_token
description: Grants the ability to create resource access tokens
boundaries:
  - project
  - group
available_for:
  - granular_access_token
permissions:
  - create_resource_access_token
