---
name: read_resource_access_token
description: Grants the ability to read resource access tokens
boundaries:
  - project
  - group
available_for:
  - granular_access_token
permissions:
  - read_resource_access_token
