---
name: read_cd_environment
description: Grants the ability to read continuous deployment environments
boundaries:
  - instance
available_for:
  - granular_access_token
permissions:
  - read_cd_environment
