# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :test do
  gem "climate_control", "~> 1.2.0"
  gem "gitlab-styles", "~> 13.0.2"
  gem "pry", "~> 0.15.2"
  gem "rspec", "~> 3.13"
  gem "simplecov", "~> 0.22.0"
end
