# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in gitlab-http.gemspec
gemspec

group :development, :test do
  gem 'gitlab-rspec', path: '../gitlab-rspec'
end

gem 'gitlab-utils', path: '../gitlab-utils'
