---
name: Secrets Manager Trial
description: Grants the ability to <actions> a Secrets Manager trial for a top-level group, which also provisions that group's secrets manager on GitLab.com, or for the whole instance.
