---
name: delete_add_on_assignment
description: Grants the ability to remove add-on seat assignments from users.
boundaries:
  - group
  - instance
available_for:
  - granular_access_token
permissions:
  - delete_add_on_assignment
