# frozen_string_literal: true

if stable_branch.non_security_stable_branch?
  markdown(<<~MARKDOWN)
  ### QA `e2e:package-and-test`

  **@#{helper.mr_author}, the `package-and-test` job must complete before merging this merge request.***

  If there are failures on the `package-and-test` pipeline, ping your team's associated Software Engineer in Test (SET) to confirm
  the failures are unrelated to the merge request. If there's no SET assigned, ask for assistance on the `#quality` Slack channel.
  MARKDOWN
end

stable_branch.check!
