---
name: mobile_push_notifications_dispatch
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/248026
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/607603
milestone: '19.3'
type: development
group: group::work items
default_enabled: false
