---
name: work_items_autocomplete
description: Enable work items in autocomplete and recent items search instead of issues
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/588616
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/233268
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/600240
milestone: '19.0'
group: group::global search
type: development
default_enabled: true
