---
name: rotate_personal_access_token
description: Grants the ability to rotate personal access tokens
boundaries:
  - user
available_for:
  - granular_access_token
permissions:
  - rotate_personal_access_token
