# frozen_string_literal: true

require 'fast_spec_helper'

RSpec.describe 'gitlab:openapi:v2 namespace rake tasks', :silence_stdout, feature_category: :api do
  before :all do
    Rake.application.rake_require 'tasks/gitlab/openapi/v2'
    Rake::Task.define_task(:environment)
    Rake::Task.define_task(:enable_feature_flags)
  end

  let(:yaml_doc_introduction) do
    <<~INTRO
    #############################################################################################
    # This documentation is auto-generated by a script.                                         #
    # Please do not edit this file directly.                                                    #
    #                                                                                           #
    # To edit the introductory text, modify `lib/tasks/gitlab/openapi/v2.rake`.                 #
    #                                                                                           #
    # Run `bin/rake gitlab:openapi:v2:generate`                                                 #
    #############################################################################################

    INTRO
  end

  shared_examples_for 'gitlab:openapi:v2:validate' do
    let(:expected_yarn_command) { 'yarn swagger:validate doc/api/openapi/openapi_v2.yaml' }

    context 'when in development environment' do
      before do
        allow(Rails).to receive_message_chain(:env, :development?).and_return(true)
      end

      it 'validates the OpenAPI documentation' do
        expect(main_object).to receive(:system).with(expected_yarn_command).and_return(true)
        run_rake_task('gitlab:openapi:v2:validate')
      end

      context 'when the validation succeeds' do
        it 'completes successfully' do
          allow(main_object).to receive(:system).with(expected_yarn_command).and_return(true)
          expect { run_rake_task('gitlab:openapi:v2:validate') }.not_to raise_error
        end
      end

      context 'when the validation fails' do
        before do
          allow(main_object).to receive(:system).with(expected_yarn_command).and_return(false)
        end

        it 'aborts with the expected error message' do
          expect { run_rake_task('gitlab:openapi:v2:validate') }
            .to raise_error(SystemExit).and output(/Validation of swagger document failed/).to_stderr
        end
      end
    end

    context 'when not in development environment' do
      before do
        allow(Rails).to receive_message_chain(:env, :development?).and_return(false)
      end

      it 'raises the expected RuntimeError error' do
        expect { run_rake_task('gitlab:openapi:v2:validate') }
          .to raise_error(RuntimeError, 'This task can only be run in the development environment')
      end
    end
  end

  shared_examples_for 'gitlab:openapi:v2:generate' do
    let(:json_content) { '{"key": "value"}' }
    let(:yaml_content) { "---\nkey: value\n" }

    before do
      allow(Rake::Task['oapi:fetch']).to receive(:invoke)
      allow(File).to receive(:read).with('tmp/openapi_swagger_doc.json').and_return(json_content)
      allow(File).to(
        receive(:read).with(Rails.root.join('deprecations/tasks/gitlab/openapi/v2_rake.yml').to_s).and_call_original
      )
    end

    it 'generates the OpenAPI documentation' do
      expect(ENV).to receive(:[]=).with('store', 'tmp/openapi.json')
      expect(Rake::Task['oapi:fetch']).to receive(:invoke).with(['openapi.json'])
      expect(File).to receive(:write).with(
        'doc/api/openapi/openapi_v2.yaml',
        yaml_doc_introduction + yaml_content
      )

      run_rake_task('gitlab:openapi:v2:generate')
    end

    context 'when not on test or development environments' do
      before do
        allow(Rails).to receive_message_chain(:env, :test?).and_return(false)
        allow(Rails).to receive_message_chain(:env, :development?).and_return(false)
      end

      it 'raises an error' do
        expect { run_rake_task('gitlab:openapi:v2:generate') }
          .to raise_error(RuntimeError, 'This task can only be run in the development or test environment')
      end
    end
  end

  describe 'gitlab:openapi:v2:validate' do
    it_behaves_like 'gitlab:openapi:v2:validate'
  end

  describe 'gitlab:openapi:v2:generate' do
    it_behaves_like 'gitlab:openapi:v2:generate'
  end

  describe 'gitlab:openapi:v2:generate_and_check' do
    it_behaves_like 'gitlab:openapi:v2:validate'
    it_behaves_like 'gitlab:openapi:v2:generate'
  end

  describe 'gitlab:openapi:v2:check_docs' do
    let(:documentation) { {} }

    before do
      allow(Rake::Task['oapi:fetch']).to receive(:invoke)
      allow(File).to receive(:read).and_call_original
      allow(File).to receive(:read).with('tmp/openapi_swagger_doc.json').and_return('{}')
      allow(File).to receive(:read).with('doc/api/openapi/openapi_v2.yaml')
        .and_return(yaml_doc_introduction + documentation.to_yaml)
    end

    it 'passes when documentation is up to date' do
      expect { run_rake_task('gitlab:openapi:v2:check_docs') }
        .to output(/OpenAPI documentation is up to date/).to_stdout
    end

    context 'when documentation is outdated' do
      let(:documentation) { { 'outdated' => true } }

      it 'aborts when documentation is outdated' do
        expect { run_rake_task('gitlab:openapi:v2:check_docs') }.to raise_error(SystemExit)
      end

      it 'outputs correct message when documentation is outdated' do
        expected_output = /OpenAPI documentation is outdated!/

        expect { run_rake_task('gitlab:openapi:v2:check_docs') }.to output(expected_output).to_stdout
          .and raise_error(SystemExit)
      end
    end

    context 'when debug is enabled' do
      let(:documentation) { { 'outdated' => true } }
      let(:verbose) { Rake::FileUtilsExt.verbose }
      let(:nowrite) { Rake::FileUtilsExt.nowrite }

      before do
        stub_env('OPENAPI_CHECK_DEBUG', 'true')

        Rake::FileUtilsExt.verbose(false)
        Rake::FileUtilsExt.nowrite(true)

        allow(File).to receive(:write).with('doc/api/openapi/openapi_v2.yaml.generated', anything)
      end

      after do
        Rake::FileUtilsExt.verbose(verbose)
        Rake::FileUtilsExt.nowrite(nowrite)
      end

      it 'outputs a diff' do
        expected_command = 'diff -u doc/api/openapi/openapi_v2.yaml doc/api/openapi/openapi_v2.yaml.generated'

        expect(main_object).to receive(:sh).with(expected_command).and_return(true)
        expect { run_rake_task('gitlab:openapi:v2:check_docs') }.to raise_error(SystemExit)
      end
    end
  end
end
