# frozen_string_literal: true

# rubocop:disable Style/SignalException

default_branch = ENV['CI_DEFAULT_BRANCH'] || 'main'

if gitlab.mr_body.size < 5
  fail "Please provide a proper merge request description."
end

unless gitlab.mr_json["assignee"]
  warn "This merge request does not have any assignee yet. Setting an assignee clarifies who needs to take action on the merge request at any given time."
end

has_milestone = !gitlab.mr_json["milestone"].nil?

unless has_milestone || (helper.security_mr? && helper.mr_target_branch == default_branch)
  warn "This merge request does not refer to an existing milestone.", sticky: false
end
