---
api_type:
attr: secrets_manager_instance_add_on_requested_at
clusterwide: true
column: secrets_manager_instance_add_on_requested_at
db_type: timestamp
default:
description: Timestamp when an administrator enabled the paid Secrets Manager add-on for the instance without a trial
encrypted: false
gitlab_com_different_than_default: false
jihu: false
not_null: false
