---
api_type:
attr: secrets_manager_instance_enrolled
clusterwide: true
column: secrets_manager_instance_enrolled
db_type: boolean
default: 'false'
description:
encrypted: false
gitlab_com_different_than_default: false
jihu: false
not_null: true
