---
api_type:
attr: tool_approval_for_session_enabled
clusterwide: false
column: tool_approval_for_session_enabled
db_type: boolean
default: 'true'
description:
encrypted: false
gitlab_com_different_than_default: false
jihu: false
not_null: true
