---
name: drop_stuck_builds_from_ci_pending_builds_queue
description: |
  Changes the `drop_stuck` query to fetch from `ci_pending_builds` instead of `p_ci_builds` and use
  EachBatch batching strategy.
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/595216
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/229567
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/595334
milestone: '18.11'
group: group::ci platform
type: gitlab_com_derisk
default_enabled: false
