---
name: merge_request_ready_flow_trigger
description:
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/592454
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/233605
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/598421
milestone: '19.0'
group: group::ai coding
type: gitlab_com_derisk
default_enabled: false
