---
name: protected_terraform_states
feature_issue_url: https://gitlab.com/groups/gitlab-org/-/epics/15118
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/228202
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/593962
milestone: '18.11'
group: group::runner core
type: gitlab_com_derisk
default_enabled: false
