---
name: request_cost_headers
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/230708
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/601092
milestone: '19.2'
type: gitlab_com_derisk
group: group::tenant_scale
default_enabled: false
