---
name: service_accounts_available_on_free_or_unlicensed
description: Allow service account creation on free tier (SaaS) and starter/unlicensed (self-managed) with a limit of 100
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/540776
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/225722
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/591930
milestone: '18.10'
group: group::authentication
type: gitlab_com_derisk
default_enabled: false
