---
name: track_api_request_from_personal_access_token
description: Track API requests authenticated via a Personal Access Token
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/580477
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/230954
rollout_issue_url: 'https://gitlab.com/gitlab-org/gitlab/-/work_items/596560'
milestone: '19.0'
group: group::authorization
type: gitlab_com_derisk
default_enabled: false
