---
name: validate_flow_trigger_filter_fields
description:
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/597413
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/248878
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/608340
milestone: '19.3'
group: group::dap events
type: gitlab_com_derisk
default_enabled: false
