# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in gitlab-utils.gemspec
gemspec

group :development, :test do
  gem 'gitlab-rspec', path: '../gitlab-rspec'
end
