#import "./work_item_current_user_todos.fragment.graphql"

# @feature_category: team_planning
mutation workItemUpdateCurrentUserTodos(
  $input: WorkItemUpdateInput!
  $useWorkItemFeatures: Boolean = false
) {
  workItemUpdate(input: $input) {
    workItem {
      id
      widgets(onlyTypes: [CURRENT_USER_TODOS]) @skip(if: $useWorkItemFeatures) {
        ...WorkItemCurrentUserTodos
      }
      features @include(if: $useWorkItemFeatures) {
        currentUserTodos {
          ...WorkItemCurrentUserTodos
        }
      }
    }
    errors
  }
}
