---
name: create_placeholder_reassignment
description: Grants the ability to create placeholder reassignments
boundaries:
  - group
available_for:
  - granular_access_token
permissions:
  - create_placeholder_reassignment
