---
name: mark_database_migration
description: Grants the ability to mark database migrations
boundaries:
  - instance
available_for:
  - granular_access_token
permissions:
  - mark_database_migration
