---
name: transfer_project
description: Grants the ability to transfer projects to a new namespace
boundaries:
  - project
  - instance
available_for:
  - granular_access_token
permissions:
  - transfer_project
