---
description: User clicks the Analytics tab on the CI/CD Catalog resource detail page
internal_events: true
status: active
action: click_component_usage_tab_on_ci_catalog
identifiers:
  - user
product_group: pipeline_authoring
product_categories:
  - component_catalog
milestone: '19.0'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/233812
tiers:
  - free
  - premium
  - ultimate
