---
description: User creates CI config file from any source
internal_events: true
action: create_ci_config_file
identifiers:
  - project
  - user
  - namespace
product_group: pipeline_authoring
product_categories:
  - pipeline_composition
milestone: '18.11'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/228244
tiers:
  - free
  - premium
  - ultimate
