---
description: Events where a project is restored
internal_events: true
status: active
action: trigger_restore_on_project
identifiers:
  - project
  - namespace
  - user
additional_properties:
  label:
    description: Location from where the restore occurred
product_group: organizations
product_categories:
  - groups_and_projects
milestone: '18.10'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/224844
tiers:
  - free
  - premium
  - ultimate
