---
description: Admin views the Set up your profile page
internal_events: true
status: active
action: view_setup_profile_page
identifiers:
  - user
product_group: acquisition
product_categories:
  - onboarding
milestone: '19.0'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/234659
tiers:
  - free
  - premium
  - ultimate
