# frozen_string_literal: true

# This is a GitLab-specific JSON interface. You should use this instead
# of using `JSON` directly. This allows us to swap the adapter and handle
# legacy issues.

require 'bigdecimal'
require 'json'
require 'oj'
require 'stringio'
require 'yajl'
require 'active_support/core_ext/numeric/bytes'
require_relative 'json/stream_validator'

module Gitlab
  module Json
    INVALID_LEGACY_TYPES = [String, TrueClass, FalseClass].freeze

    PARSE_LIMITS = {
      max_depth: 32,
      max_array_size: 50000,
      max_hash_size: 50000,
      max_total_elements: 100000,
      max_json_size_bytes: 20.megabytes
    }.freeze

    class << self
      attr_accessor :on_limit_exceeded, :on_oversize_object

      # Parse a string and convert it to a Ruby object
      #
      # @param string [String] the JSON string to convert to Ruby objects
      # @param opts [Hash] an options hash in the standard JSON gem format
      # @return [Boolean, String, Array, Hash]
      # @raise [JSON::ParserError] raised if parsing fails
      def parse(string, opts = {})
        # Parse nil as nil
        return if string.nil?

        # First we should ensure this really is a string, not some other
        # type which purports to be a string. This handles some legacy
        # usage of the JSON class.
        string = string.to_s unless string.is_a?(String)

        legacy_mode = legacy_mode_enabled?(opts.delete(:legacy_mode))

        log_oversize_object(string)

        data = adapter_load(string, **opts)

        handle_legacy_mode!(data) if legacy_mode

        data
      end

      alias_method :parse!, :parse
      alias_method :load, :parse
      alias_method :decode, :parse

      # Parse a string and convert it to a Ruby object, but with limits
      #
      # @param string [String] the JSON string to convert to Ruby objects
      # @param opts [Hash] an options hash in the standard JSON gem format
      # @return [Boolean, String, Array, Hash]
      # @raise [JSON::ParserError] raised if parsing fails
      def safe_parse(string, opts = {})
        return if string.nil?

        parse_limits = PARSE_LIMITS.merge(opts.delete(:parse_limits) || {})

        validate!(string, parse_limits)

        parse(string, opts)
      end

      # Restricted method for converting a Ruby object to JSON. If you
      # need to pass options to this, you should use `.generate` instead,
      # as the underlying implementation of this varies wildly based on
      # the adapter in use.
      #
      # This method does, in some situations, differ in the data it returns
      # compared to .generate. Counter-intuitively, this is closest in
      # terms of response to JSON.generate and to the default ActiveSupport
      # .to_json method.
      #
      # @param object [Object] the object to convert to JSON
      # @return [String]
      def dump(object)
        adapter_dump(object)
      end

      # Generates JSON for an object. In Oj this takes fewer options than .dump,
      # in the JSON gem this is the only method which takes an options argument.
      #
      # @param object [Hash, Array, Object] must be hash, array, or an object that responds to .to_h or .to_json
      # @param opts [Hash] an options hash with fewer supported settings than .dump
      # @return [String]
      def generate(object, opts = {})
        adapter_generate(object, opts)
      end

      alias_method :encode, :generate

      # Generates JSON for an object and makes it look purdy
      #
      # The Oj variant in this looks seriously weird but these are the settings
      # needed to emulate the style generated by the JSON gem.
      #
      # NOTE: This currently ignores Oj, because Oj doesn't generate identical
      #       formatting, issue: https://github.com/ohler55/oj/issues/608
      #
      # @param object [Hash, Array, Object] must be hash, array, or an object that responds to .to_h or .to_json
      # @param opts [Hash] an options hash with fewer supported settings than .dump
      # @return [String]
      def pretty_generate(object, opts = {})
        ::JSON.pretty_generate(object, opts)
      end

      # The standard parser error we should be returning. Defined in a method
      # so we can potentially override it later.
      #
      # @return [JSON::ParserError]
      def parser_error
        ::JSON::ParserError
      end

      private

      # Convert JSON string into Ruby through toggleable adapters.
      #
      # Must rescue adapter-specific errors and return `parser_error`, and
      # must also standardize the options hash to support each adapter as
      # they all take different options.
      #
      # @param string [String] the JSON string to convert to Ruby objects
      # @param opts [Hash] an options hash in the standard JSON gem format
      # @return [Boolean, String, Array, Hash]
      # @raise [JSON::ParserError]
      def adapter_load(string, *_args, **opts)
        opts = standardize_opts(opts)

        Oj.load(string, opts)
      rescue Oj::ParseError, EncodingError, Encoding::UndefinedConversionError, JSON::GeneratorError => e
        raise parser_error, e
      end

      def validate!(string, parse_limits)
        Gitlab::Json::StreamValidator.new(parse_limits).validate!(string)
      rescue Oj::ParseError, EncodingError => e
        raise parser_error, e
      rescue ::Gitlab::Json::StreamValidator::LimitExceededError => e
        log_exceeded_json(e, parse_limits)
        message = ::Gitlab::Json::StreamValidator.user_facing_error_message(e)
        raise parser_error, message
      end

      def log_exceeded_json(exception, parse_limits)
        on_limit_exceeded&.call(exception, parse_limits)
      end

      # Take a Ruby object and convert it to a string. This method varies
      # based on the underlying JSON interpreter. Oj treats this like JSON
      # treats `.generate`. JSON.dump takes no options.
      #
      # This supports these options to ensure this difference is recorded here,
      # as it's very surprising. The public interface is more restrictive to
      # prevent adapter-specific options being passed.
      #
      # @overload adapter_dump(object, opts)
      #   @param object [Object] the object to convert to JSON
      #   @param opts [Hash] options as named arguments, only supported by Oj
      #
      # @overload adapter_dump(object, anIO, limit)
      #   @param object [Object] the object, will have JSON.generate called on it
      #   @param anIO [Object] an IO-like object that responds to .write, default nil
      #   @param limit [Fixnum] the nested array/object limit, default nil
      #   @raise [ArgumentError] when depth limit exceeded
      #
      # @return [String]
      def adapter_dump(object, *_args, **opts)
        opts = standardize_opts(opts)

        Oj.dump(object, opts)
      end

      # Generates JSON for an object but with fewer options, using toggleable adapters.
      #
      # @param object [Hash, Array, Object] must be hash, array, or an object that responds to .to_h or .to_json
      # @param opts [Hash] an options hash with fewer supported settings than .dump
      # @return [String]
      def adapter_generate(object, opts = {})
        opts = standardize_opts(opts)

        Oj.generate(object, opts)
      end

      # Take a JSON standard options hash and standardize it to work across adapters
      # An example of this is Oj taking :symbol_keys instead of :symbolize_names
      #
      # @param opts [Hash, Nil]
      # @return [Hash]
      def standardize_opts(opts)
        opts ||= {}
        opts[:mode] = :rails
        opts[:symbol_keys] = opts[:symbolize_keys] || opts[:symbolize_names]

        opts
      end

      # @param [Nil, Boolean] an extracted :legacy_mode key from the opts hash
      # @return [Boolean]
      def legacy_mode_enabled?(arg_value)
        arg_value.nil? ? false : arg_value
      end

      # If legacy mode is enabled, we need to raise an error depending on the values
      # provided in the string. This will be deprecated.
      #
      # @param data [Boolean, String, Array, Hash, Object]
      # @return [Boolean, String, Array, Hash, Object]
      # @raise [JSON::ParserError]
      def handle_legacy_mode!(data)
        raise parser_error if INVALID_LEGACY_TYPES.any? { |type| data.is_a?(type) }
      end

      def log_oversize_object(string)
        on_oversize_object&.call(string)
      end
    end

    # Wrapper class used to skip JSON dumping on Grape endpoints.

    class Precompiled
      UnsupportedFormatError = Class.new(StandardError)

      # @overload Precompiled.new("foo")
      #   @param value [String]
      #
      # @overload Precompiled.new(["foo", "bar"])
      #   @param value [Array<String>]
      def initialize(value)
        @value = value
      end

      # Convert the value to a String. This will invoke
      # `#to_s` on the members of the value if it's an array.
      #
      # @return [String]
      # @raise [NoMethodError] if the objects in an array doesn't support to_s
      # @raise [Precompiled::UnsupportedFormatError] if the value is neither a String or Array
      def to_s
        return @value if @value.is_a?(String)
        return "[#{@value.join(',')}]" if @value.is_a?(Array)

        raise UnsupportedFormatError
      end

      def render_in(_view_context)
        to_s
      end

      def format
        :json
      end
    end

    class LimitedEncoder
      LimitExceeded = Class.new(StandardError)
      NumberLimitExceeded = Class.new(StandardError)

      # Maximum number of digits a numeric value may produce when serialized.
      # Numbers exceeding this are rejected to prevent denial-of-service via
      # values like 9E9999999 which expand to billions of characters.
      # 1 000 digits is generous for any legitimate use case (e.g. Unix
      # timestamps are 10 digits, financial amounts rarely exceed 20).
      MAXIMUM_NUMERIC_DIGITS = 1_000

      # Generates JSON for an object or raise an error if the resulting json string is too big
      # or if the object contains a number that would serialize to too many digits.
      #
      # @param object [Hash, Array, Object] must be hash, array, or an object that responds to .to_h or .to_json
      # @param limit [Integer] max size of the resulting json string
      # @return [String]
      # @raise [LimitExceeded] if the resulting json string is bigger than the specified limit
      # @raise [NumberLimitExceeded] if a numeric value would serialize to more than MAXIMUM_NUMERIC_DIGITS digits
      def self.encode(object, limit: 25.megabytes)
        check_numbers!(object)

        buffer = StringIO.new
        buffer_size = 0

        ::Yajl::Encoder.encode(object) do |data_chunk|
          chunk_size = data_chunk.bytesize

          raise LimitExceeded if buffer_size + chunk_size > limit

          buffer << data_chunk
          buffer_size += chunk_size
        end

        buffer.string
      end

      # Recursively checks that no numeric value in the object would produce
      # a dangerously long string when serialized to JSON.
      #
      # This is intentionally public so that callers (e.g. model validations)
      # can reuse the same check without duplicating the logic.
      #
      # @raise [NumberLimitExceeded] if an unsafe numeric value is found
      def self.check_numbers!(value)
        case value
        when BigDecimal, Float, Integer
          # BigDecimal#exponent is constant-time and tells us the digit count
          # of the integer part. Negative exponents mean small decimals like
          # 0.000...001 which also expand to many characters in fixed notation.
          bd = BigDecimal(value.to_s)
          raise NumberLimitExceeded unless bd.finite?
          raise NumberLimitExceeded if bd.exponent.abs > MAXIMUM_NUMERIC_DIGITS
        when Hash
          value.each_value { |v| check_numbers!(v) }
        when Array
          value.each { |v| check_numbers!(v) }
        end
      end
    end
  end
end
