---
name: cells_claims_pages_domains
description: Gates the Cells claims integration for the PagesDomain model
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/473017
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/241865
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/473017
milestone: '19.2'
group: group::planner intelligence
type: beta
default_enabled: false
