---
name: custom_code_dropdown_clients
description: Allow admins to configure custom "Open with" clients in the project Code dropdown
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/604390
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/244658
rollout_issue_url:
milestone: '19.4'
group: group::source code
type: beta
default_enabled: false
