---
name: group_dependency_vulnerabilities_graphql
description:
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/600268
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/236273
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/600835
milestone: '19.1'
group: group::security insights
type: beta
default_enabled: true
