---
name: repository_changed_paths_api
description: Enables the GET /projects/:id/repository/changed_paths REST API endpoint
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/234458
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/605935
milestone: '19.4'
group: group::gitaly
type: beta
default_enabled: false
