---
name: use_new_branches_finder_api
description:
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/578546
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/229216
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/594929
milestone: '19.0'
group: group::source code
type: beta
default_enabled: false
