---
name: vue3_migrate_contribution_analytics
description: Enables Vue 3 in compatibility mode for the group contribution analytics page
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/607822
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/248655
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/608138
milestone: '19.3'
group: group::optimize
type: beta
default_enabled: false
