---
name: vue3_migrate_refs_management
description: Enables Vue 3 for the refs management pages (branches and tags index, show, and new).
feature_issue_url: https://gitlab.com/groups/gitlab-org/-/work_items/23084
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/251075
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/613674
milestone: '19.4'
group: group::source code
type: beta
default_enabled: false
