---
name: vue3_migrate_pipelines
description: Enables Vue 3 in compatibility mode for pipelines lists and details
feature_issue_url: https://gitlab.com/groups/gitlab-org/-/work_items/20939
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/228275
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/594278
milestone: '19.0'
group: group::ci platform
type: beta
default_enabled: false
