---
name: vue3_migrate_mr_list
description: Enables Vue 3 in compatibility mode for the project merge requests list page
feature_issue_url: https://gitlab.com/groups/gitlab-org/-/work_items/23167
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/255790
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/611464
milestone: '19.4'
group: group::code review
type: beta
default_enabled: false
