<script>
import { GlIntersperse } from '@gitlab/ui';

export default {
  name: 'ListPresenter',
  components: {
    GlIntersperse,
  },
  inject: ['presenter'],
  props: {
    data: {
      required: true,
      type: Object,
      validator: ({ nodes }) => Array.isArray(nodes),
    },
    config: {
      required: true,
      type: Object,
      validator: ({ fields }) => Array.isArray(fields) && fields.length > 0,
    },
    listType: {
      required: false,
      type: String,
      default: 'ul',
      validator: (value) => ['ul', 'ol'].includes(value),
    },
  },
  computed: {
    items() {
      return this.data.nodes || [];
    },
    fields() {
      return this.config.fields;
    },
  },
};
</script>
<template>
  <div class="gl-mb-4">
    <component :is="listType" class="!gl-mb-1" data-testid="list">
      <li
        v-for="(item, itemIndex) in items"
        :key="itemIndex"
        :data-testid="`list-item-${itemIndex}`"
      >
        <gl-intersperse separator=" - ">
          <span v-for="(field, fieldIndex) in fields" :key="fieldIndex">
            <component :is="presenter.forField(item, field)" />
          </span>
        </gl-intersperse>
      </li>
      <li v-if="!items.length">
        <em>{{ __('No data found for this query') }}</em>
      </li>
    </component>
    <small>{{ __('Generated by GLQL') }}</small>
  </div>
</template>
