<script>
import { toSentenceCase } from '../../utils/common';

export default {
  name: 'TablePresenter',
  inject: ['presenter'],
  props: {
    data: {
      required: true,
      type: Object,
      validator: ({ nodes }) => Array.isArray(nodes),
    },
    config: {
      required: true,
      type: Object,
      validator: ({ fields }) => Array.isArray(fields) && fields.length > 0,
    },
  },
  computed: {
    items() {
      return this.data.nodes;
    },
    fields() {
      return this.config.fields.map((field) => {
        return { key: field, label: toSentenceCase(field) };
      });
    },
  },
};
</script>
<template>
  <div class="!gl-my-4">
    <table class="!gl-mt-0 !gl-mb-2">
      <thead>
        <tr>
          <th v-for="field in fields" :key="field.key">
            {{ field.label }}
          </th>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="(item, itemIndex) in items"
          :key="itemIndex"
          :data-testid="`table-row-${itemIndex}`"
        >
          <td v-for="(field, fieldIndex) in fields" :key="fieldIndex">
            <component :is="presenter.forField(item, field.key)" />
          </td>
        </tr>
        <tr v-if="!items.length">
          <td :colspan="fields.length" class="gl-text-center">
            <em>{{ __('No data found for this query') }}</em>
          </td>
        </tr>
      </tbody>
    </table>
    <small>{{ __('Generated by GLQL') }}</small>
  </div>
</template>
