export const mockCiLintJobs = [
  {
    beforeScript: [],
    afterScript: [],
    environment: null,
    allowFailure: false,
    tags: [],
    when: 'on_success',
    only: { refs: ['branches', 'tags'], __typename: 'CiConfigJobRestriction' },
    except: null,
    needs: [],
    __typename: 'CiConfigJobV2',
    name: 'job_test_1',
    script: ['echo "test 1"'],
    stage: 'test',
  },
  {
    name: 'job_test_2',
    script: ['echo "test 2"'],
    stage: 'test',
    beforeScript: [],
    afterScript: [],
    environment: null,
    allowFailure: false,
    tags: [],
    when: 'on_success',
    only: { refs: ['branches', 'tags'], __typename: 'CiConfigJobRestriction' },
    except: null,
    needs: [],
    __typename: 'CiConfigJobV2',
  },
  {
    name: 'job_build',
    script: ['echo "build"'],
    stage: 'build',
    beforeScript: [],
    afterScript: [],
    environment: null,
    allowFailure: false,
    tags: [],
    when: 'on_success',
    only: { refs: ['branches', 'tags'], __typename: 'CiConfigJobRestriction' },
    except: null,
    needs: [
      { name: 'job_test_1', __typename: 'CiConfigNeed' },
      { name: 'job_test_2', __typename: 'CiConfigNeed' },
    ],
    __typename: 'CiConfigJobV2',
  },
];
