---
name: delete_access_request
description: Grants the ability to delete access requests
boundaries:
  - group
  - project
  - user
available_for:
  - granular_access_token
permissions:
  - delete_access_request
