# frozen_string_literal: true

class ValidateSubscriptionUserAddOnAssignmentVersionsOrgFkCascade < Gitlab::Database::Migration[2.3]
  milestone '19.1'

  # The new FK name generated by add_concurrent_foreign_key (fk_ prefix)
  FK_NAME = :fk_091e013a61
  TABLE_NAME = :subscription_user_add_on_assignment_versions
  COLUMN_NAME = :organization_id

  def up
    validate_foreign_key TABLE_NAME, COLUMN_NAME, name: FK_NAME
  end

  def down
    # no-op: validation cannot be reversed
  end
end
