---
name: create_cluster_agent_url_configuration
description: Grants the ability to create cluster agent URL configurations
boundaries:
  - project
available_for:
  - granular_access_token
permissions:
  - create_cluster_agent_url_configuration
