# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in gitlab-housekeeper.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"
gem "pry"
gem 'webmock'
gem 'rspec-parameterized', '~> 1.0', '>= 1.0.2', require: false

group :development, :test do
  gem 'gitlab-rspec', path: '../gitlab-rspec'
end
