#import "~/graphql_shared/fragments/page_info.fragment.graphql"
#import "../fragments/organization.fragment.graphql"

query getCurrentUserOrganizations(
  $search: String
  $first: Int
  $last: Int
  $before: String
  $after: String
  $excludeDefault: Boolean = false
  $state: OrganizationState = null
) {
  currentUser {
    id
    organizations(
      search: $search
      first: $first
      last: $last
      before: $before
      after: $after
      excludeDefault: $excludeDefault
      state: $state
    ) {
      nodes {
        ...Organization
      }
      pageInfo {
        ...PageInfo
      }
    }
  }
}
