#!/bin/bash

set -xe

# Create sshd daemon
mkdir -p /opt/gitlab/sv/sshd/supervise
mkfifo /opt/gitlab/sv/sshd/supervise/ok
printf "#!/bin/sh\nexec 2>&1\numask 077\nexec /usr/sbin/sshd -D" > /opt/gitlab/sv/sshd/run
chmod a+x /opt/gitlab/sv/sshd/run
ln -s /opt/gitlab/sv/sshd /opt/gitlab/service
mkdir -p /var/run/sshd

# Disabling use DNS in ssh since it tends to slow connecting
echo "UseDNS no" >> /etc/ssh/sshd_config
