#!/bin/bash

function sigterm_handler() {
    echo "SIGTERM signal received, try to gracefully shutdown all services..."
    gitlab-ctl stop
}

trap "sigterm_handler; exit" TERM

set -xe

if [[ ! -e /etc/gitlab/gitlab.rb ]]; then
	cp /assets/gitlab.rb /etc/gitlab/gitlab.rb
	chmod 0600 /etc/gitlab/gitlab.rb
fi

gitlab-ctl reconfigure # start everything
gitlab-ctl tail # all logs
