# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in active_context.gemspec
gemspec

gem "rake", "~> 13.0"
gem "activesupport"

group :development, :test do
  gem "rspec", "~> 3.0"
  gem "byebug"
  gem "rubocop"
  gem "rubocop-rspec"
end
