export const diffMetadata = {
  real_size: '1',
  size: 1,
  branch_name: 'update-changelog',
  source_branch_exists: true,
  target_branch_name: 'main',
  commit: null,
  context_commits: null,
  merge_request_diff: {
    version_index: null,
    created_at: '2019-11-07T06:48:35.202Z',
    commits_count: 1,
    latest: true,
    short_commit_sha: 'eb227b3e',
    base_version_path: '/gitlab-org/gitlab-test/-/merge_requests/4/diffs?diff_id=4',
    head_version_path: '/gitlab-org/gitlab-test/-/merge_requests/4/diffs?diff_head=true',
    version_path: '/gitlab-org/gitlab-test/-/merge_requests/4/diffs?diff_id=4',
    compare_path:
      '/gitlab-org/gitlab-test/-/merge_requests/4/diffs?diff_id=4\u0026start_sha=eb227b3e214624708c474bdab7bde7afc17cefcc',
  },
  start_version: null,
  latest_diff: true,
  latest_version_path: '/gitlab-org/gitlab-test/-/merge_requests/4/diffs',
  added_lines: 2,
  removed_lines: 0,
  render_overflow_warning: false,
  email_patch_path: '/gitlab-org/gitlab-test/-/merge_requests/4.patch',
  plain_diff_path: '/gitlab-org/gitlab-test/-/merge_requests/4.diff',
  has_encoded_file_paths: false,
  merge_request_diffs: [
    {
      version_index: null,
      created_at: '2019-11-07T06:48:35.202Z',
      commits_count: 1,
      latest: true,
      short_commit_sha: 'eb227b3e',
      base_version_path: '/gitlab-org/gitlab-test/-/merge_requests/4/diffs?diff_id=4',
      head_version_path: '/gitlab-org/gitlab-test/-/merge_requests/4/diffs?diff_head=true',
      version_path: '/gitlab-org/gitlab-test/-/merge_requests/4/diffs?diff_id=4',
      compare_path:
        '/gitlab-org/gitlab-test/-/merge_requests/4/diffs?diff_id=4\u0026start_sha=eb227b3e214624708c474bdab7bde7afc17cefcc',
    },
  ],
  diff_files: [
    {
      added_lines: 2,
      removed_lines: 0,
      new_path: 'CHANGELOG',
      old_path: 'CHANGELOG',
      new_file: false,
      deleted_file: false,
      file_identifier_hash: '928f8286952bda02d674b692addcbe077084663a',
      file_hash: '1c497fbb3a46b78edf04cc2a2fa33f67e3ffbe2a',
    },
  ],
};
