export default {
  id: '6b232e05bea388c6b043ccc243ba505faac04ea8',
  reply_id: '6b232e05bea388c6b043ccc243ba505faac04ea8',
  position: {
    old_line: null,
    new_line: 2,
    old_path: 'CHANGELOG',
    new_path: 'CHANGELOG',
    base_sha: 'e63f41fe459e62e1228fcef60d7189127aeba95a',
    start_sha: 'd9eaefe5a676b820c57ff18cf5b68316025f7962',
    head_sha: 'c48ee0d1bf3b30453f5b32250ce03134beaa6d13',
  },
  line_code: '1c497fbb3a46b78edf04cc2a2fa33f67e3ffbe2a_1_2',
  expanded: true,
  notes: [
    {
      id: '1749',
      type: 'DiffNote',
      attachment: null,
      author: {
        id: 1,
        name: 'Administrator',
        username: 'root',
        state: 'active',
        avatar_url:
          'https://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=80&d=identicon',
        path: '/root',
      },
      created_at: '2018-04-03T21:06:21.521Z',
      updated_at: '2018-04-08T08:50:41.762Z',
      system: false,
      noteable_id: 51,
      noteable_type: 'MergeRequest',
      noteable_iid: 20,
      human_access: 'Owner',
      note: 'comment 1',
      note_html: '<p dir="auto">comment 1</p>',
      last_edited_at: '2018-04-08T08:50:41.762Z',
      last_edited_by: {
        id: 1,
        name: 'Administrator',
        username: 'root',
        state: 'active',
        avatar_url:
          'https://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=80&d=identicon',
        path: '/root',
      },
      current_user: {
        can_edit: true,
        can_award_emoji: true,
      },
      resolved: false,
      resolvable: true,
      resolved_by: null,
      discussion_id: '6b232e05bea388c6b043ccc243ba505faac04ea8',
      emoji_awardable: true,
      award_emoji: [],
      toggle_award_path: '/gitlab-org/gitlab-test/notes/1749/toggle_award_emoji',
      report_abuse_path:
        '/abuse_reports/new?ref_url=http%3A%2F%2Flocalhost%3A3000%2Fgitlab-org%2Fgitlab-test%2Fmerge_requests%2F20%23note_1749&user_id=1',
      path: '/gitlab-org/gitlab-test/notes/1749',
      noteable_note_url: 'http://localhost:3000/gitlab-org/gitlab-test/merge_requests/20#note_1749',
      resolve_path:
        '/gitlab-org/gitlab-test/merge_requests/20/discussions/6b232e05bea388c6b043ccc243ba505faac04ea8/resolve',
      resolve_with_issue_path:
        '/gitlab-org/gitlab-test/issues/new?discussion_to_resolve=6b232e05bea388c6b043ccc243ba505faac04ea8&merge_request_to_resolve_discussions_of=20',
    },
    {
      id: '1753',
      type: 'DiffNote',
      attachment: null,
      author: {
        id: 1,
        name: 'Fatih Acet',
        username: 'fatihacet',
        state: 'active',
        avatar_url:
          'https://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=80&d=identicon',
        path: '/fatihacevt',
      },
      created_at: '2018-04-08T08:49:35.804Z',
      updated_at: '2018-04-08T08:50:45.915Z',
      system: false,
      noteable_id: 51,
      noteable_type: 'MergeRequest',
      noteable_iid: 20,
      human_access: 'Owner',
      note: 'comment 2 is really long one',
      note_html: '<p dir="auto">comment 2 is really long one</p>',
      last_edited_at: '2018-04-08T08:50:45.915Z',
      last_edited_by: {
        id: 1,
        name: 'Administrator',
        username: 'root',
        state: 'active',
        avatar_url:
          'https://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=80&d=identicon',
        path: '/root',
      },
      current_user: {
        can_edit: true,
        can_award_emoji: true,
      },
      resolved: false,
      resolvable: true,
      resolved_by: null,
      discussion_id: '6b232e05bea388c6b043ccc243ba505faac04ea8',
      emoji_awardable: true,
      award_emoji: [],
      toggle_award_path: '/gitlab-org/gitlab-test/notes/1753/toggle_award_emoji',
      report_abuse_path:
        '/abuse_reports/new?ref_url=http%3A%2F%2Flocalhost%3A3000%2Fgitlab-org%2Fgitlab-test%2Fmerge_requests%2F20%23note_1753&user_id=1',
      path: '/gitlab-org/gitlab-test/notes/1753',
      noteable_note_url: 'http://localhost:3000/gitlab-org/gitlab-test/merge_requests/20#note_1753',
      resolve_path:
        '/gitlab-org/gitlab-test/merge_requests/20/discussions/6b232e05bea388c6b043ccc243ba505faac04ea8/resolve',
      resolve_with_issue_path:
        '/gitlab-org/gitlab-test/issues/new?discussion_to_resolve=6b232e05bea388c6b043ccc243ba505faac04ea8&merge_request_to_resolve_discussions_of=20',
    },
    {
      id: '1754',
      type: 'DiffNote',
      attachment: null,
      author: {
        id: 1,
        name: 'Administrator',
        username: 'root',
        state: 'active',
        avatar_url:
          'https://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=80&d=identicon',
        path: '/root',
      },
      created_at: '2018-04-08T08:50:48.294Z',
      updated_at: '2018-04-08T08:50:48.294Z',
      system: false,
      noteable_id: 51,
      noteable_type: 'MergeRequest',
      noteable_iid: 20,
      human_access: 'Owner',
      note: 'comment 3',
      note_html: '<p dir="auto">comment 3</p>',
      current_user: {
        can_edit: true,
        can_award_emoji: true,
      },
      resolved: false,
      resolvable: true,
      resolved_by: null,
      discussion_id: '6b232e05bea388c6b043ccc243ba505faac04ea8',
      emoji_awardable: true,
      award_emoji: [],
      toggle_award_path: '/gitlab-org/gitlab-test/notes/1754/toggle_award_emoji',
      report_abuse_path:
        '/abuse_reports/new?ref_url=http%3A%2F%2Flocalhost%3A3000%2Fgitlab-org%2Fgitlab-test%2Fmerge_requests%2F20%23note_1754&user_id=1',
      path: '/gitlab-org/gitlab-test/notes/1754',
      noteable_note_url: 'http://localhost:3000/gitlab-org/gitlab-test/merge_requests/20#note_1754',
      resolve_path:
        '/gitlab-org/gitlab-test/merge_requests/20/discussions/6b232e05bea388c6b043ccc243ba505faac04ea8/resolve',
      resolve_with_issue_path:
        '/gitlab-org/gitlab-test/issues/new?discussion_to_resolve=6b232e05bea388c6b043ccc243ba505faac04ea8&merge_request_to_resolve_discussions_of=20',
    },
    {
      id: '1755',
      type: 'DiffNote',
      attachment: null,
      author: {
        id: 1,
        name: 'Administrator',
        username: 'root',
        state: 'active',
        avatar_url:
          'https://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=80&d=identicon',
        path: '/root',
      },
      created_at: '2018-04-08T08:50:50.911Z',
      updated_at: '2018-04-08T08:50:50.911Z',
      system: false,
      noteable_id: 51,
      noteable_type: 'MergeRequest',
      noteable_iid: 20,
      human_access: 'Owner',
      note: 'comment 4',
      note_html: '<p dir="auto">comment 4</p>',
      current_user: {
        can_edit: true,
        can_award_emoji: true,
      },
      resolved: false,
      resolvable: true,
      resolved_by: null,
      discussion_id: '6b232e05bea388c6b043ccc243ba505faac04ea8',
      emoji_awardable: true,
      award_emoji: [],
      toggle_award_path: '/gitlab-org/gitlab-test/notes/1755/toggle_award_emoji',
      report_abuse_path:
        '/abuse_reports/new?ref_url=http%3A%2F%2Flocalhost%3A3000%2Fgitlab-org%2Fgitlab-test%2Fmerge_requests%2F20%23note_1755&user_id=1',
      path: '/gitlab-org/gitlab-test/notes/1755',
      noteable_note_url: 'http://localhost:3000/gitlab-org/gitlab-test/merge_requests/20#note_1755',
      resolve_path:
        '/gitlab-org/gitlab-test/merge_requests/20/discussions/6b232e05bea388c6b043ccc243ba505faac04ea8/resolve',
      resolve_with_issue_path:
        '/gitlab-org/gitlab-test/issues/new?discussion_to_resolve=6b232e05bea388c6b043ccc243ba505faac04ea8&merge_request_to_resolve_discussions_of=20',
    },
    {
      id: '1756',
      type: 'DiffNote',
      attachment: null,
      author: {
        id: 1,
        name: 'Administrator',
        username: 'root',
        state: 'active',
        avatar_url:
          'https://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=80&d=identicon',
        path: '/root',
      },
      created_at: '2018-04-08T08:50:53.895Z',
      updated_at: '2018-04-08T08:50:53.895Z',
      system: false,
      noteable_id: 51,
      noteable_type: 'MergeRequest',
      noteable_iid: 20,
      human_access: 'Owner',
      note: 'comment 5',
      note_html: '<p dir="auto">comment 5</p>',
      current_user: {
        can_edit: true,
        can_award_emoji: true,
      },
      resolved: false,
      resolvable: true,
      resolved_by: null,
      discussion_id: '6b232e05bea388c6b043ccc243ba505faac04ea8',
      emoji_awardable: true,
      award_emoji: [],
      toggle_award_path: '/gitlab-org/gitlab-test/notes/1756/toggle_award_emoji',
      report_abuse_path:
        '/abuse_reports/new?ref_url=http%3A%2F%2Flocalhost%3A3000%2Fgitlab-org%2Fgitlab-test%2Fmerge_requests%2F20%23note_1756&user_id=1',
      path: '/gitlab-org/gitlab-test/notes/1756',
      noteable_note_url: 'http://localhost:3000/gitlab-org/gitlab-test/merge_requests/20#note_1756',
      resolve_path:
        '/gitlab-org/gitlab-test/merge_requests/20/discussions/6b232e05bea388c6b043ccc243ba505faac04ea8/resolve',
      resolve_with_issue_path:
        '/gitlab-org/gitlab-test/issues/new?discussion_to_resolve=6b232e05bea388c6b043ccc243ba505faac04ea8&merge_request_to_resolve_discussions_of=20',
    },
  ],
  individual_note: false,
  resolvable: true,
  resolved: false,
  resolve_path:
    '/gitlab-org/gitlab-test/merge_requests/20/discussions/6b232e05bea388c6b043ccc243ba505faac04ea8/resolve',
  resolve_with_issue_path:
    '/gitlab-org/gitlab-test/issues/new?discussion_to_resolve=6b232e05bea388c6b043ccc243ba505faac04ea8&merge_request_to_resolve_discussions_of=20',
  diff_file: {
    submodule: false,
    submodule_link: null,
    blob: {
      id: '9e10516ca50788acf18c518a231914a21e5f16f7',
      path: 'CHANGELOG',
      name: 'CHANGELOG',
      mode: '100644',
      readable_text: true,
      icon: 'doc-text',
    },
    blob_path: 'CHANGELOG',
    blob_name: 'CHANGELOG',
    file_hash: '1c497fbb3a46b78edf04cc2a2fa33f67e3ffbe2a',
    file_path: 'CHANGELOG.rb',
    new_file: false,
    deleted_file: false,
    renamed_file: false,
    old_path: 'CHANGELOG',
    new_path: 'CHANGELOG',
    mode_changed: false,
    a_mode: '100644',
    b_mode: '100644',
    text: true,
    added_lines: 2,
    removed_lines: 0,
    diff_refs: {
      base_sha: 'e63f41fe459e62e1228fcef60d7189127aeba95a',
      start_sha: 'd9eaefe5a676b820c57ff18cf5b68316025f7962',
      head_sha: 'c48ee0d1bf3b30453f5b32250ce03134beaa6d13',
    },
    content_sha: 'c48ee0d1bf3b30453f5b32250ce03134beaa6d13',
    stored_externally: null,
    external_storage: null,
    old_path_html: 'CHANGELOG_OLD',
    new_path_html: 'CHANGELOG',
    is_fully_expanded: true,
    context_lines_path:
      '/gitlab-org/gitlab-test/blob/c48ee0d1bf3b30453f5b32250ce03134beaa6d13/CHANGELOG/diff',
    highlighted_diff_lines: [
      {
        line_code: '1c497fbb3a46b78edf04cc2a2fa33f67e3ffbe2a_1_1',
        type: 'new',
        old_line: null,
        new_line: 1,
        text: '<span id="LC1" class="line" lang="plaintext">  - Bad dates</span>\n',
        rich_text: '<span id="LC1" class="line" lang="plaintext">  - Bad dates</span>\n',
        meta_data: null,
      },
      {
        line_code: '1c497fbb3a46b78edf04cc2a2fa33f67e3ffbe2a_1_2',
        type: 'new',
        old_line: null,
        new_line: 2,
        text: '<span id="LC2" class="line" lang="plaintext"></span>\n',
        rich_text: '<span id="LC2" class="line" lang="plaintext"></span>\n',
        meta_data: null,
      },
      {
        line_code: '1c497fbb3a46b78edf04cc2a2fa33f67e3ffbe2a_1_3',
        type: null,
        old_line: 1,
        new_line: 3,
        text: '<span id="LC3" class="line" lang="plaintext">v6.8.0</span>\n',
        rich_text: '<span id="LC3" class="line" lang="plaintext">v6.8.0</span>\n',
        meta_data: null,
      },
      {
        line_code: '1c497fbb3a46b78edf04cc2a2fa33f67e3ffbe2a_2_4',
        type: null,
        old_line: 2,
        new_line: 4,
        text: '<span id="LC4" class="line" lang="plaintext"></span>\n',
        rich_text: '<span id="LC4" class="line" lang="plaintext"></span>\n',
        meta_data: null,
      },
      {
        line_code: '1c497fbb3a46b78edf04cc2a2fa33f67e3ffbe2a_3_5',
        type: null,
        old_line: 3,
        new_line: 5,
        text: ' <span id="LC5" class="line" lang="plaintext">v6.7.0</span>\n',
        rich_text: ' <span id="LC5" class="line" lang="plaintext">v6.7.0</span>\n',
        meta_data: null,
      },
      {
        line_code: null,
        type: 'match',
        old_line: null,
        new_line: null,
        text: '',
        rich_text: '',
        meta_data: {
          old_pos: 3,
          new_pos: 5,
        },
      },
      {
        line_code: null,
        type: 'match',
        old_line: null,
        new_line: null,
        text: '',
        rich_text: '',
        meta_data: {
          old_pos: 3,
          new_pos: 5,
        },
      },
      {
        line_code: null,
        type: 'match',
        old_line: null,
        new_line: null,
        text: '',
        rich_text: '',
        meta_data: {
          old_pos: 3,
          new_pos: 5,
        },
      },
    ],
    parallel_diff_lines: [
      {
        left: null,
        right: {
          line_code: '1c497fbb3a46b78edf04cc2a2fa33f67e3ffbe2a_1_1',
          type: 'new',
          old_line: null,
          new_line: 1,
          text: '<span id="LC1" class="line" lang="plaintext">  - Bad dates</span>\n',
          rich_text: '<span id="LC1" class="line" lang="plaintext">  - Bad dates</span>\n',
          meta_data: null,
        },
      },
      {
        left: null,
        right: {
          line_code: '1c497fbb3a46b78edf04cc2a2fa33f67e3ffbe2a_1_2',
          type: 'new',
          old_line: null,
          new_line: 2,
          text: '<span id="LC2" class="line" lang="plaintext"></span>\n',
          rich_text: '<span id="LC2" class="line" lang="plaintext"></span>\n',
          meta_data: null,
        },
      },
      {
        left: {
          line_code: '1c497fbb3a46b78edf04cc2a2fa33f67e3ffbe2a_1_3',
          type: null,
          old_line: 1,
          new_line: 3,
          text: '<span id="LC3" class="line" lang="plaintext">v6.8.0</span>\n',
          rich_text: '<span id="LC3" class="line" lang="plaintext">v6.8.0</span>\n',
          meta_data: null,
        },
        right: {
          line_code: '1c497fbb3a46b78edf04cc2a2fa33f67e3ffbe2a_1_3',
          type: null,
          old_line: 1,
          new_line: 3,
          text: '<span id="LC3" class="line" lang="plaintext">v6.8.0</span>\n',
          rich_text: '<span id="LC3" class="line" lang="plaintext">v6.8.0</span>\n',
          meta_data: null,
        },
      },
      {
        left: {
          line_code: '1c497fbb3a46b78edf04cc2a2fa33f67e3ffbe2a_2_4',
          type: null,
          old_line: 2,
          new_line: 4,
          text: '<span id="LC4" class="line" lang="plaintext"></span>\n',
          rich_text: '<span id="LC4" class="line" lang="plaintext"></span>\n',
          meta_data: null,
        },
        right: {
          line_code: '1c497fbb3a46b78edf04cc2a2fa33f67e3ffbe2a_2_4',
          type: null,
          old_line: 2,
          new_line: 4,
          text: '<span id="LC4" class="line" lang="plaintext"></span>\n',
          rich_text: '<span id="LC4" class="line" lang="plaintext"></span>\n',
          meta_data: null,
        },
      },
      {
        left: {
          line_code: '1c497fbb3a46b78edf04cc2a2fa33f67e3ffbe2a_3_5',
          type: null,
          old_line: 3,
          new_line: 5,
          text: ' <span id="LC5" class="line" lang="plaintext">v6.7.0</span>\n',
          rich_text: ' <span id="LC5" class="line" lang="plaintext">v6.7.0</span>\n',
          meta_data: null,
        },
        right: {
          line_code: '1c497fbb3a46b78edf04cc2a2fa33f67e3ffbe2a_3_5',
          type: null,
          old_line: 3,
          new_line: 5,
          text: ' <span id="LC5" class="line" lang="plaintext">v6.7.0</span>\n',
          rich_text: ' <span id="LC5" class="line" lang="plaintext">v6.7.0</span>\n',
          meta_data: null,
        },
      },
      {
        left: {
          line_code: null,
          type: 'match',
          old_line: null,
          new_line: null,
          text: '',
          rich_text: '',
          meta_data: {
            old_pos: 3,
            new_pos: 5,
          },
        },
        right: {
          line_code: null,
          type: 'match',
          old_line: null,
          new_line: null,
          text: '',
          rich_text: '',
          meta_data: {
            old_pos: 3,
            new_pos: 5,
          },
        },
      },
    ],
    viewer: {
      name: 'text',
      error: null,
    },
  },
  diff_discussion: true,
  truncated_diff_lines: [
    {
      text: 'line',
      rich_text:
        '<tr class="line_holder new" id="">\n<td class="diff-line-num new old_line" data-linenumber="1">\n \n</td>\n<td class="diff-line-num new new_line" data-linenumber="1">\n1\n</td>\n<td class="line_content new"><span id="LC1" class="line" lang="plaintext">  - Bad dates</span>\n</td>\n</tr>\n<tr class="line_holder new" id="">\n<td class="diff-line-num new old_line" data-linenumber="1">\n \n</td>\n<td class="diff-line-num new new_line" data-linenumber="2">\n2\n</td>\n<td class="line_content new"><span id="LC2" class="line" lang="plaintext"></span>\n</td>\n</tr>\n',
      can_receive_suggestion: true,
      line_code: '6f209374f7e565f771b95720abf46024c41d1885_1_1',
      type: 'new',
      old_line: null,
      new_line: 1,
      meta_data: null,
    },
  ],
};

export const imageDiffDiscussions = [
  {
    id: '1',
    position: {
      x: 10,
      y: 10,
      width: 100,
      height: 200,
    },
  },
  {
    id: '2',
    position: {
      x: 5,
      y: 5,
      width: 100,
      height: 200,
    },
  },
];
