---
name: cancel_bulk_import
description: Grants the ability to cancel a GitLab Migration (bulk import)
deprecated: true
boundaries:
  - instance
available_for:
  - granular_access_token
permissions:
  - cancel_bulk_import
