---
name: create_work_item_saved_view
description: Grants the ability to create work item saved views
boundaries:
  - group
  - project
available_for:
  - granular_access_token
permissions:
  - create_work_item_saved_view
