# frozen_string_literal: true

module Gitlab
  module Import
    class IidPreallocator
      # PostgreSQL integer type max value (2^31 - 1).
      # The internal_ids.last_value column is an integer, so we must reject
      # values that would overflow it. This also prevents DoS via extremely
      # large IID reservations from maliciously crafted export archives.
      MAX_VALID_IID = (2**31) - 1

      # Maps each CE resource type to a tracker lambda and a scope_resolver lambda.
      #
      # tracker: called with (scope_value, max_iid) to pre-allocate the IID.
      #   Uses the track_*_iid! class methods generated by AtomicInternalId.
      #   See app/models/concerns/atomic_internal_id.rb
      #
      # scope_resolver: called with the importable (Project or Group) to resolve
      #   the correct scope object. Returns nil for inapplicable scopes (e.g.
      #   group_milestones on a project with no group) - execute skips those.
      #
      # valid_for: specifies which importable types this resource applies to.
      #   Array of symbols, e.g. [:project], [:group], or [:project, :group]
      #   This prevents malicious injection of project-scoped resources in group imports.
      TRACKABLE_RESOURCES = {
        issues: {
          tracker: ->(scope, iid) { ::Issue.track_namespace_iid!(scope, iid) },
          scope_resolver: ->(importable) { importable.project_namespace },
          valid_for: [:project]
        },
        merge_requests: {
          tracker: ->(scope, iid) { ::MergeRequest.track_target_project_iid!(scope, iid) },
          scope_resolver: ->(importable) { importable },
          valid_for: [:project]
        },
        project_milestones: {
          tracker: ->(scope, iid) { ::Milestone.track_project_iid!(scope, iid) },
          scope_resolver: ->(importable) { importable },
          valid_for: [:project]
        },
        group_milestones: {
          tracker: ->(scope, iid) { ::Milestone.track_group_iid!(scope, iid) },
          scope_resolver: ->(importable) { importable.is_a?(::Group) ? importable : importable.group },
          valid_for: [:project, :group]
        },
        ci_pipelines: {
          tracker: ->(scope, iid) { ::Ci::Pipeline.track_project_iid!(scope, iid) },
          scope_resolver: ->(importable) { importable },
          valid_for: [:project]
        },
        design_management_designs: {
          tracker: ->(scope, iid) { ::DesignManagement::Design.track_project_iid!(scope, iid) },
          scope_resolver: ->(importable) { importable },
          valid_for: [:project]
        }
      }.freeze

      def self.trackable_resources
        TRACKABLE_RESOURCES
      end

      def self.valid_iid_value?(value)
        value.is_a?(Integer) && value > 0 && value <= MAX_VALID_IID
      end

      def self.from_file(importable, path)
        return unless File.exist?(path)

        content = File.read(path, Gitlab::ImportExport::Json::NdjsonReader::MAX_JSON_DOCUMENT_SIZE)
        parsed = Gitlab::Json.safe_parse(content)

        unless parsed.is_a?(Hash)
          ::Import::Framework::Logger.warn(
            message: 'IidPreallocator: skipping preallocation, invalid content in max_iids file'
          )
          return
        end

        symbolized = parsed.transform_keys(&:to_sym)
        valid, invalid = symbolized.partition { |_, v| valid_iid_value?(v) }.map(&:to_h)

        if invalid.any?
          ::Import::Framework::Logger.warn(
            message: 'IidPreallocator: ignoring invalid IID entries in max_iids file',
            invalid_entries: invalid
          )
        end

        new(importable, valid).execute
      rescue EncodingError, JSON::ParserError
        ::Import::Framework::Logger.warn(
          message: 'IidPreallocator: skipping preallocation, invalid content in max_iids file'
        )
      rescue StandardError => e
        ::Import::Framework::Logger.warn(
          message: 'IidPreallocator: skipping preallocation, failed to read max_iids file',
          error: e.message
        )
      end

      # @param importable [Project, Group] the project or group being imported into
      # @param max_iids [Hash<Symbol, Integer>] resource type => max IID from source
      #   e.g. { issues: 142, merge_requests: 37, ci_pipelines: 891 }
      def initialize(importable, max_iids)
        @importable = importable
        @max_iids = max_iids
      end

      def execute
        self.class.trackable_resources.each do |resource, config|
          max_iid = @max_iids[resource]
          next unless max_iid
          next unless valid_for_importable?(config[:valid_for])

          scope_value = config[:scope_resolver].call(@importable)
          next unless scope_value

          config[:tracker].call(scope_value, max_iid)
        end
      end

      private

      def valid_for_importable?(valid_for)
        importable_type = @importable.is_a?(::Project) ? :project : :group

        valid_for.include?(importable_type)
      end
    end
  end
end

Gitlab::Import::IidPreallocator.prepend_mod
