---
name: delete_ai_catalog_item_consumer
description: Grants the ability to delete AI catalog item consumers
available_for:
  - granular_access_token
permissions:
  - delete_ai_catalog_item_consumer
boundaries:
  - project
  - group
