---
name: update_credit_card_validation
description: Grants the ability to update user credit card validations
boundaries:
  - instance
available_for:
  - granular_access_token
permissions:
  - update_credit_card_validation
