---
name: delete_secrets_permission
description: Grants the ability to delete secrets permissions
boundaries:
  - group
  - project
available_for:
  - granular_access_token
permissions:
  - delete_secrets_permission
