---
name: read_batched_background_operation
description: Grants the ability to read batched background operations
boundaries:
  - instance
available_for:
  - granular_access_token
permissions:
  - read_batched_background_operation
