---
name: read_protected_branch
description: Grants the ability to read protected branches
boundaries:
  - project
  - group
available_for:
  - granular_access_token
permissions:
  - read_protected_branch
