---
key_path: counts.count_total_scheduled_project_deletion_on_setting
description: Count of scheduled project deletion on setting actions
product_group: organizations
product_categories:
  - groups_and_projects
performance_indicator_type: []
value_type: number
status: active
milestone: '18.10'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/224842
time_frame:
  - 28d
  - 7d
  - all
data_source: internal_events
data_category: optional
tiers:
  - free
  - premium
  - ultimate
events:
  - name: trigger_delete_on_project
    filter:
      label: setting
      property: 'false'
      actor: 'user'
