---
name: create_cluster_agent_token
description: Grants the ability to create cluster agent tokens
boundaries:
  - project
available_for:
  - granular_access_token
permissions:
  - create_cluster_agent_token
