# frozen_string_literal: true

TELEMETRY_CHANGED_FILES_MESSAGE = <<~MSG
This merge request includes changes for which a review from the Data team and Telemetry team is recommended.
Please reach out to @gitlab-org/growth/telemetry/engineers group for a review.
MSG

USAGE_DATA_FILES_MESSAGE = <<~MSG
For the following files, a review from the [Data team and Telemetry team](https://gitlab.com/groups/gitlab-org/growth/telemetry/engineers/-/group_members?with_inherited_permissions=exclude) is recommended:
MSG

usage_data_changed_files = git.modified_files.grep(%r{usage_data})

if usage_data_changed_files.any?
  warn format(TELEMETRY_CHANGED_FILES_MESSAGE)

  markdown(USAGE_DATA_FILES_MESSAGE + helper.markdown_list(usage_data_changed_files))

  telemetry_labels = ['telemetry']
  telemetry_labels << 'telemetry::review pending' unless helper.mr_has_labels?('telemetry::reviewed')

  markdown(helper.prepare_labels_for_mr(telemetry_labels))
end
