---
name: read_deploy_token
description: Grants the ability to read deploy tokens
boundaries:
  - instance
  - group
  - project
available_for:
  - granular_access_token
permissions:
  - read_deploy_token
