#!/bin/sh

# script/update: Update application to run for its current checkout.

set -e

# Returns true if the working tree is dirty
clean_working_tree() {
  test -z "git diff --shortstat 2> /dev/null | tail -n1"
}

db_running()
{
  db_host=$(pwd | sed 's/gitlab/postgresql/')

  if ! (pg_isready --host="$db_host"); then
    echo "------------------------------------------------------------"
    echo "Make sure Postgres is running for host '$db_host' otherwise db:migrate will fail"
    echo "------------------------------------------------------------"
    exit 1
  fi
}

cd "$(dirname "$0")/.."

previous_head=$(git rev-parse HEAD)
current_branch=$(git rev-parse --abbrev-ref HEAD)
stash_created="false"

git checkout -- Gemfile.lock db/schema.rb locale/

if ! (clean_working_tree); then
  echo "==> Stashing the following changes (retrieve them with 'git stash pop' if needed)..."
  diff=$(git diff --name-status)
  echo $diff
  git stash
  stash_created="true"
fi

echo "==> Pulling (fast-forward only) $current_branch..."
git pull --ff-only origin $current_branch

script/bootstrap

if [ "$stash_created" = "true" ]; then
  echo "==> Retrieving stashed changes..."
  git stash pop
fi

if ! (test -z "$(git diff "$previous_head"...HEAD -- db/schema.rb 2> /dev/null | tail -n1)"); then
  db_running
  echo "==> Running all database migrations to ensure everything is up to date..."
  echo ""
  bin/rake db:migrate db:test:prepare
fi
