---
name: create_virtual_registry_cleanup_policy
description: Grants the ability to create virtual registry cleanup policies
boundaries:
  - group
available_for:
  - granular_access_token
permissions:
  - create_virtual_registry_cleanup_policy
