# frozen_string_literal: true

module Tasks
  module Gitlab
    module Openapi
      class V3Document
        INTRODUCTION = <<~INTRO
          #############################################################################################
          # This documentation is auto-generated by a script.                                         #
          # Please do not edit this file directly.                                                    #
          #                                                                                           #
          # To edit the introductory text, modify `lib/tasks/gitlab/openapi/v3_document.rb`.          #
          #                                                                                           #
          # Run `bin/rake gitlab:openapi:v3:generate`                                                 #
          #############################################################################################

        INTRO

        def self.render = new.render

        def render
          INTRODUCTION + generator.generate.deep_stringify_keys.to_yaml
        end

        private

        def generator
          ::Gitlab::GrapeOpenapi::Generator.new(api_classes: ::API::Base.descendants)
        end
      end
    end
  end
end
