---
name: delete_container_repository_protection_rule
description: Grants the ability to delete container repository protection rules
boundaries:
  - project
available_for:
  - granular_access_token
permissions:
  - delete_container_repository_protection_rule
