---
name: create_issuable_metric_image
description: Grants the ability to create issuable metric images
boundaries:
  - project
available_for:
  - granular_access_token
permissions:
  - create_issuable_metric_image
