#!/bin/sh

# Check if file exists with -f. Check if in in the gdk rook directory.
if [ ! -f ../GDK_ROOT ]; then
  echo "Please run script from gitlab (e.g. gitlab-development-kit/gitlab) root directory."
  exit 1
fi

PRECOMMIT=$(git rev-parse --git-dir)/hooks/pre-commit

# Check if symlink exists with -L. Check if script was already installed.
if [ -L $PRECOMMIT ]; then
  echo "Pre-commit script already installed."
  exit 1
fi

ln -s ./pre-commit $PRECOMMIT
echo "Pre-commit script installed successfully"
