#!/usr/bin/env ruby

WHITELIST = [
  'CHANGELOG-EE.md',
  'config/**/*', # https://gitlab.com/gitlab-org/gitlab-ee/issues/4946
  'doc/**/*', # https://gitlab.com/gitlab-org/gitlab-ee/issues/4948#note_59945483
  'qa/**/*', # https://gitlab.com/gitlab-org/gitlab-ee/issues/4997#note_59764702
  'scripts/*',
  'spec/javascripts/**/*', # https://gitlab.com/gitlab-org/gitlab-ee/issues/3871
  'vendor/assets/javascripts/jasmine-jquery.js'
].freeze

`git remote add canonical-ee https://gitlab.com/gitlab-org/gitlab-ee.git`
`git remote add canonical-ce https://gitlab.com/gitlab-org/gitlab-ce.git`
`git fetch canonical-ee master --quiet`

new_files_in_this_branch_not_at_the_ee_top_level =
  `git diff canonical-ee/master...HEAD --name-status --diff-filter=A -- ./ ':!ee' | cut -f2`.lines.map(&:strip)

ce_repo_url = ENV['CI_REPOSITORY_URL'].sub('gitlab-ee', 'gitlab-ce')
current_branch = ENV.fetch('CI_COMMIT_REF_NAME', `git rev-parse --abbrev-ref HEAD`).strip
ce_branch_name = current_branch.sub(/(\Aee\-|\-ee\z)/, '')

`git fetch #{ce_repo_url} #{ce_branch_name} --quiet` || `git fetch canonical-ce 'master' --quiet`

ee_specific_files_in_ce_master_not_at_the_ee_top_level =
  `git diff FETCH_HEAD..HEAD --name-status --diff-filter=A -- ./ ':!ee' | cut -f2`.lines.map(&:strip)
new_ee_specific_files_not_at_the_ee_top_level =
  new_files_in_this_branch_not_at_the_ee_top_level & ee_specific_files_in_ce_master_not_at_the_ee_top_level

status = 0

new_ee_specific_files_not_at_the_ee_top_level.each do |file|
  next if WHITELIST.any? { |pattern| Dir.glob(pattern).include?(file) }

  puts
  puts "* #{file} is EE-specific and should be moved to ee/#{file}:"
  puts "  => git mv #{file} ee/#{file}"
  status = 1
end

`git remote remove canonical-ee`
`git remote remove canonical-ce`

exit(status)
