#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates index.html for published development resources at
# https://gitlab-org.gitlab.io/gitlab/
#
# Known resources include a description.
#
# Usage: scripts/generate-pages-index.rb <pages_dir>
#   pages_dir: path to the directory being published as Pages (e.g. public-pages)

require 'erb'
require 'pathname'

PAGES_DIR = Pathname.new(ARGV.fetch(0, 'public-pages'))

abort "ERROR: pages directory '#{PAGES_DIR}' does not exist" unless PAGES_DIR.directory?

DESCRIPTIONS = {
  'coverage-frontend' => 'Frontend (Jest) test coverage',
  'coverage-ruby' => 'Ruby test coverage',
  'crystalball' => 'Test to source mapping',
  'knapsack' => 'Knapsack RSpec timing report',
  'rspec' => 'Flaky RSpec tests',
  'rubocop-docs' => 'RuboCop documentation site',
  'storybook' => 'Frontend component Storybook',
  'application.css' => 'Compiled production CSS'
}.freeze

TEMPLATE = <<~ERB
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GitLab Development Resources</title>
    <style>
      body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        max-width: 900px;
        margin: 40px auto;
        padding: 0 20px;
        color: #333;
      }
      h1 { color: #fc6d26; border-bottom: 2px solid #fc6d26; padding-bottom: 10px; }
      p { color: #555; }
      table { border-collapse: collapse; width: 100%; margin-top: 20px; }
      th {
        text-align: left;
        padding: 10px 14px;
        background: #f5f5f5;
        border-bottom: 2px solid #ddd;
        font-size: 0.85em;
        text-transform: uppercase;
        letter-spacing: 0.05em;
        color: #666;
      }
      td { padding: 10px 14px; border-bottom: 1px solid #eee; vertical-align: top; }
      td:nth-child(2) { white-space: nowrap; color: #888; font-size: 0.9em; font-variant-numeric: tabular-nums; }
      td:nth-child(3) { color: #666; font-size: 0.9em; }
      a { color: #1f75cb; text-decoration: none; }
      a:hover { text-decoration: underline; }
      tr:last-child td { border-bottom: none; }
      footer { margin-top: 32px; color: #555; font-size: 0.85em; }
    </style>
  </head>
  <body>
    <h1>GitLab Development Resources</h1>
    <p>
      Development artifacts generated by scheduled CI pipelines for the
      <a href="https://gitlab.com/gitlab-org/gitlab">gitlab-org/gitlab</a> project.
    </p>
    <table>
      <thead>
        <tr>
          <th>Resource</th>
          <th>Size</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        <%- entries.each do |e| -%>
        <tr>
          <td><a href="<%= e.href %>"><%= e.href %></a></td>
          <td><%= e.size %></td>
          <td><%= e.description %></td>
        </tr>
        <%- end -%>
      </tbody>
    </table>

    <footer>
      <%= footer %>
    </footer>
  </body>
  </html>
ERB

class Entry
  include Comparable

  def initialize(path)
    @path = path
  end

  def description
    DESCRIPTIONS[basename]
  end

  def href
    @href ||= "#{basename}#{'/' if path.directory?}"
  end

  def size
    `du -sh #{path} 2>/dev/null`.split("\t", 2).first || '-'
  end

  def <=>(other)
    sort_rank <=> other.sort_rank
  end

  protected

  # Sort by name ASC, directories on top.
  def sort_rank
    [path.directory? ? 0 : 1, href]
  end

  private

  attr_reader :path

  def basename
    path.basename.to_s
  end
end

footer = proc do
  timestamp = Time.now.utc.strftime("%F %T %Z")

  pipeline_url = ENV['CI_PIPELINE_URL']
  via = pipeline_url ? %(by <a href="#{ERB::Util.html_escape(pipeline_url)}">pipeline</a>) : 'locally'

  %(Generated at #{timestamp} #{via}.)
end

entries = PAGES_DIR
  .each_child
  .map { |path| Entry.new(path) }
  .select(&:description) # skip unmapped entries
  .sort

output = PAGES_DIR.join('index.html')
content = ERB
  .new(TEMPLATE, trim_mode: '-')
  .result_with_hash(entries: entries, footer: footer.call)
File.write(output, content)

puts "Generated #{output}"
