#!/usr/bin/env ruby

# This script is used both in CI and in local development 'rspec' runs.

require_relative 'gitaly_test'

class GitalyTestSpawn
  include GitalyTest

  def run
    install_gitaly_gems if ENV['CI']
    check_gitaly_config!

    # # Uncomment line below to see all gitaly logs merged into CI trace
    # spawn('sleep 1; tail -f log/gitaly-test.log')

    # In local development this pid file is used by rspec.
    IO.write(File.expand_path('../tmp/tests/gitaly.pid', __dir__), start_gitaly)
    IO.write(File.expand_path('../tmp/tests/gitaly2.pid', __dir__), start_gitaly2)
    IO.write(File.expand_path('../tmp/tests/praefect.pid', __dir__), start_praefect)
  end
end

GitalyTestSpawn.new.run
