#!/usr/bin/env ruby

gitaly_dir = 'tmp/tests/gitaly'
gitaly_ruby_dir = File.expand_path(File.join(gitaly_dir, 'ruby'))
env = { 'HOME' => File.expand_path('tmp/tests'),
        'GEM_PATH' => Gem.path.join(':'),
        'BUNDLE_IGNORE_CONFIG' => 'true',
        'BUNDLE_GEMFILE' => File.join(gitaly_ruby_dir, 'Gemfile') }

unless ENV['CI'].to_s.empty?
  env['BUNDLE_PATH'] = File.expand_path('../vendor', __dir__)
end

args = %W[#{gitaly_dir}/gitaly #{gitaly_dir}/config.toml]

spawn('sleep 1; tail -f log/gitaly-test.log')
system(env, 'bundle', 'config', chdir: gitaly_ruby_dir)

# Print the PID of the spawned process
puts spawn(env, *args, [:out, :err] => 'log/gitaly-test.log')
