#!/bin/sh

# This script assumes tmp/tests/gitaly already contains the correct
# Gitaly version. We just have to compile it and run its 'bundle
# install'. We have this separate script for that because weird things
# were happening in CI when we have a 'bundle exec' process that later
# called 'bundle install' using a different Gemfile, as happens with
# gitlab-ce and gitaly.

dir='tmp/tests/gitaly'

if ! (
  cd "${dir}" && make BUNDLE_FLAGS=--no-deployment
); then
  echo 'gitaly build failed'
  exit 1
fi

# Make the 'gitaly' executable look newer than 'GITALY_SERVER_VERSION'.
# Without this a gitaly executable created in the setup-test-env job
# will look stale compared to GITALY_SERVER_VERSION.
touch -t 210001010000 "${dir}/gitaly"
