#!/usr/bin/env ruby

require 'fileutils'

require_relative 'gitaly_test'

# This script assumes tmp/tests/gitaly already contains the correct
# Gitaly version. We just have to compile it and run its 'bundle
# install'. We have this separate script for that to avoid bundle
# poisoning in CI. This script should only be run in CI.
class GitalyTestBuild
  include GitalyTest

  def run
    abort 'gitaly build failed' unless system(env, 'make', chdir: tmp_tests_gitaly_dir)

    check_gitaly_config!

    # Starting gitaly further validates its configuration
    pid = start_gitaly
    Process.kill('TERM', pid)

    # Make the 'gitaly' executable look newer than 'GITALY_SERVER_VERSION'.
    # Without this a gitaly executable created in the setup-test-env job
    # will look stale compared to GITALY_SERVER_VERSION.
    FileUtils.touch(File.join(tmp_tests_gitaly_dir, 'gitaly'), mtime: Time.now + (1 << 24))
  end
end

GitalyTestBuild.new.run
