#!/bin/sh

lint_paths="changelogs/unreleased"
[ -d "ee/" ] && lint_paths="$lint_paths ee/changelogs/unreleased"

invalid_files=$(find $lint_paths -type f -not -name "*.yml" -not -name ".gitkeep")

if [ -n "$invalid_files" ]; then
    echo "Changelog files must end in .yml, but these did not:"
    echo "$invalid_files" | sed -e "s/^/* /"
  exit 1
fi
