#!/usr/bin/env ruby

# frozen_string_literal: true

require_relative './database/migration_checksum_checker'

result = MigrationChecksumChecker.new.check

if result
  puts result.error_message
  exit result.error_code
end
