---
name: create_runner_controller
description: Grants the ability to create runner controllers
boundaries:
  - instance
available_for:
  - granular_access_token
permissions:
  - create_runner_controller
