---
name: create_protected_environment
description: Grants the ability to create protected environments
boundaries:
  - project
  - group
available_for:
  - granular_access_token
permissions:
  - create_protected_environment
