---
name: update_protected_environment
description: Grants the ability to update protected environments
boundaries:
  - project
  - group
available_for:
  - granular_access_token
permissions:
  - update_protected_environment
