# frozen_string_literal: true

# Make sure to run `make` (in this directory) when you update this file.
source 'https://rubygems.org'

gem 'overcommit'
gem 'gitlab-styles', '~> 4.2.0', require: false
gem 'scss_lint', '~> 0.56.0', require: false
gem 'haml_lint', '~> 0.34.0', require: false
