# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :test do
  gem "climate_control", "~> 1.2.0"
  gem "gitlab-styles", "~> 14.0.0"
  gem "pry", "~> 0.16.0"
  gem "rspec", "~> 3.13", ">= 3.13.2"
  gem "simplecov", "~> 0.22.0"
end
