# frozen_string_literal: true

return if stable_branch.valid_stable_branch?

product_intelligence.check!

product_intelligence.check_affected_scopes!

product_intelligence.check_usage_data_insertions!
