.bundle/
danger/
doc/
log/*.log
node_modules/
rubocop/
tmp/*

db/fixtures/
!db/fixtures/development/01_admin.rb
!db/fixtures/development/02_application_settings.rb
!db/fixtures/development/25_api_personal_access_token.rb

ee/db/fixtures/
!ee/db/fixtures/development/10_license_file.rb

scripts/
!scripts/frontend

qa/
!qa/gdk
