.bundle/
builds/
changelogs/
danger/
data/
doc/
rubocop/
storybook/
log/*.log
node_modules/
tmp/*

*.md

db/fixtures/
!db/fixtures/development/01_admin.rb
!db/fixtures/development/02_application_settings.rb
!db/fixtures/development/25_api_personal_access_token.rb

ee/db/fixtures/
!ee/db/fixtures/development/10_license_file.rb

scripts/
!scripts/frontend

qa/
!qa/gdk

spec/
!spec/contracts
!spec/factories
!spec/support

ee/spec
!ee/spec/contracts
!ee/spec/factories
!ee/spec/support
