# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in gitlab-safe_request_store.gemspec
gemspec

group :development, :test do
  gem 'gitlab-rspec', path: '../gitlab-rspec'
end

gem 'activerecord-gitlab', path: '../activerecord-gitlab'
gem 'gitlab-utils', path: '../gitlab-utils'
gem 'gitlab-safe_request_store', path: '../gitlab-safe_request_store'
