---
name: create_terraform_state_protection_rule
description: Grants the ability to create Terraform state protection rules
boundaries:
  - project
available_for:
  - granular_access_token
permissions:
  - create_terraform_state_protection_rule
