---
name: ci_register_job_full_queue_count
description:
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/593402
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/229077
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/594931
milestone: '18.11'
group: group::pipeline execution
type: ops
default_enabled: false
