/**
 * Regenerate the baselines the frontend package boundary rules are ratcheted against.
 *
 * Usage:
 *   node scripts/frontend/generate_dependency_cruiser_todo.mjs             # every rule
 *   node scripts/frontend/generate_dependency_cruiser_todo.mjs no-shared-layer-imports-from-features
 *
 * Each generated file under `.dependency_cruiser_todo/` lists the files that violate one rule
 * today, and `config/dependency_cruiser.mjs` feeds that list back in as `from.pathNot`. The rules
 * therefore only fail on *new* violations. The lists are a high-water mark: they should only ever
 * shrink, so run this after fixing violations, never to make a new one pass.
 *
 * The rule definitions are read from `config/dependency_cruiser.mjs` itself (with
 * `REVEAL_DEPS_TODO=1`, so the existing baselines are ignored) rather than duplicated here. That
 * way a baseline can never drift from the rule CI actually enforces.
 */
import fs from 'node:fs';
import path from 'node:path';
import { program } from 'commander';
import * as prettier from 'prettier';
import { cruise } from 'dependency-cruiser';
// eslint-disable-next-line import/no-unresolved -- valid subpath export that the resolver misses
import extractWebpackResolveConfig from 'dependency-cruiser/config-utl/extract-webpack-resolve-config';

const ROOT_PATH = path.resolve(import.meta.dirname, '../../');
const TODO_DIR = '.dependency_cruiser_todo';

// Rules whose violations are baselined in a todo file. `no-circular` is deliberately absent: its
// known violations are suppressed via the `doNotFollow` exclusions list in the config instead.
const RATCHETED_RULES = ['no-imports-from-entrypoints', 'no-shared-layer-imports-from-features'];

// EE and JH ship their frontend as optional source overlays that are absent on FOSS checkouts, so
// only cruise the roots this checkout actually has. Mirrors scripts/frontend/trace_provide_inject_usage.mjs.
const ASSET_ROOTS = [
  'app/assets/javascripts',
  'ee/app/assets/javascripts',
  'jh/app/assets/javascripts',
].filter((dir) => fs.existsSync(path.join(ROOT_PATH, dir)));

async function prettify(data) {
  const prettierConfig = await prettier.resolveConfig(path.join(ROOT_PATH, '.prettierrc'));
  return prettier.format(data, { ...prettierConfig, parser: 'babel' });
}

/**
 * Cruise both asset roots once and return the violating `from` paths grouped by rule name.
 *
 * @returns {Promise<Map<string, string[]>>}
 */
async function collectViolations() {
  // Must be set before the config is imported: it decides whether the existing baselines are
  // applied, and we need them ignored so every current violation is reported.
  process.env.REVEAL_DEPS_TODO = '1';
  const { default: depcruiseConfig } = await import('../../config/dependency_cruiser.mjs');
  const resolveOptions = await extractWebpackResolveConfig('./config/webpack.config.js');

  // `webpackConfig` is how the CLI derives resolve options; we pass them explicitly instead.
  const { webpackConfig, ...options } = depcruiseConfig.options;

  const { output } = await cruise(
    ASSET_ROOTS,
    {
      ...options,
      ruleSet: { forbidden: depcruiseConfig.forbidden },
      // Without this every dependency is reported as valid and the run finds nothing at all.
      validate: true,
      // The cache is keyed loosely enough that it can serve a report generated for a different
      // rule set, which silently produces an empty baseline.
      cache: false,
    },
    resolveOptions,
  );

  const byRule = new Map(RATCHETED_RULES.map((rule) => [rule, new Set()]));
  for (const violation of output.summary.violations) {
    byRule.get(violation.rule.name)?.add(violation.from);
  }
  return new Map([...byRule].map(([rule, files]) => [rule, [...files].sort()]));
}

async function writeTodoFile(rule, offendingFiles) {
  const todoFilePath = path.join(ROOT_PATH, TODO_DIR, `${rule}.mjs`);
  const entries = offendingFiles.map((file) => JSON.stringify(file)).join(',\n');

  const contents = `
    /**
     * Generated by \`node scripts/frontend/generate_dependency_cruiser_todo.mjs ${rule}\`.
     *
     * Each entry is the path of one file exempted from the rule. Prefer fixing it to extending the list.
     */
    export default {
      files: [${entries}],
    }
    `;

  fs.writeFileSync(todoFilePath, await prettify(contents));
  console.log(`${rule}: wrote ${offendingFiles.length} entries to ${TODO_DIR}/${rule}.mjs`);
}

async function main() {
  program
    .description(
      'Regenerates the .dependency_cruiser_todo baselines for the frontend boundary rules.',
    )
    .argument('[rule]', `one of: ${RATCHETED_RULES.join(', ')} (default: all)`)
    .parse();

  const [requestedRule] = program.args;
  if (requestedRule && !RATCHETED_RULES.includes(requestedRule)) {
    console.error(
      `Unknown rule "${requestedRule}". Expected one of: ${RATCHETED_RULES.join(', ')}.`,
    );
    process.exitCode = 1;
    return;
  }

  const violations = await collectViolations();
  const rules = requestedRule ? [requestedRule] : RATCHETED_RULES;
  await Promise.all(rules.map((rule) => writeTodoFile(rule, violations.get(rule) ?? [])));
}

await main();
