---
name: read_error_tracking_setting
description: Grants the ability to read error tracking settings
boundaries:
  - project
available_for:
  - granular_access_token
permissions:
  - read_error_tracking_setting
