# This CI job is responsible for the contents of development
# support web site at https://gitlab-org.gitlab.io/

.compress-pages: &compress-pages
  - find "$PAGES_DIR" -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|json\|css\|svg\|xml\)$' -exec gzip -f -k {} \;
  - find "$PAGES_DIR" -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|json\|css\|svg\|xml\)$' -exec brotli -f -k {} \;

upload-pages:
  extends:
    - .default-retry
    - .pages:rules
  stage: pages
  environment: pages
  resource_group: pages
  needs:
    - "rspec:coverage"
    - "coverage-frontend"
    - "compile-production-assets"
    - "compile-storybook"
    - "update-tests-metadata"
    - "generate-frontend-fixtures-mapping"
    - "rubocop:docs-site"
  variables:
    PAGES_DIR: "public-pages"
  before_script:
    - apt-get update && apt-get -y install brotli gzip
  script:
    - mkdir "$PAGES_DIR"
    - cp public/assets/application-*.css $PAGES_DIR/application.css || true
    - mv coverage/ $PAGES_DIR/coverage-ruby/ || true
    - mv coverage-frontend/ $PAGES_DIR/coverage-frontend/ || true
    - mv rubocop/docs-hugo/public/ $PAGES_DIR/rubocop-docs/ || true
    - mv storybook/public $PAGES_DIR/storybook || true
    - |
      (cd "$PAGES_DIR" && mkdir -p \
        $(dirname "$KNAPSACK_RSPEC_SUITE_REPORT_PATH") \
        $(dirname "$FLAKY_RSPEC_SUITE_REPORT_PATH") \
        $(dirname "$GLCI_PREDICTIVE_RSPEC_PACKED_TESTS_MAPPING_PATH") \
        $(dirname "$GLCI_PREDICTIVE_RSPEC_PACKED_TESTS_MAPPING_ALT_PATH") \
        $(dirname "$GLCI_PREDICTIVE_FRONTEND_FIXTURES_MAPPING_PATH")
      )
    - mv $KNAPSACK_RSPEC_SUITE_REPORT_PATH $PAGES_DIR/$KNAPSACK_RSPEC_SUITE_REPORT_PATH || true
    - mv $FLAKY_RSPEC_SUITE_REPORT_PATH $PAGES_DIR/$FLAKY_RSPEC_SUITE_REPORT_PATH || true
    - mv $GLCI_PREDICTIVE_RSPEC_PACKED_TESTS_MAPPING_PATH.gz $PAGES_DIR/$GLCI_PREDICTIVE_RSPEC_PACKED_TESTS_MAPPING_PATH.gz || true
    - mv $GLCI_PREDICTIVE_RSPEC_PACKED_TESTS_MAPPING_ALT_PATH.gz $PAGES_DIR/$GLCI_PREDICTIVE_RSPEC_PACKED_TESTS_MAPPING_ALT_PATH.gz || true
    - mv $GLCI_PREDICTIVE_FRONTEND_FIXTURES_MAPPING_PATH $PAGES_DIR/$GLCI_PREDICTIVE_FRONTEND_FIXTURES_MAPPING_PATH || true
    - *compress-pages
  pages:
    publish: $PAGES_DIR
    expire_in: 31d
