#!/usr/bin/env ruby

# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))

require 'gitlab/cng/cli'

Signal.trap('INT') do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

module Cng
  def self.run
    Gitlab::Cng::CLI.start
  rescue Gitlab::Cng::CLI::Error => e
    puts "ERROR: #{e.message}"
    exit 1
  end
end

Cng.run
