---
name: delete_timelog
description: Grants the ability to delete timelogs that track time spent on issuables
boundaries:
  - project
available_for:
  - granular_access_token
permissions:
  - delete_timelog
